server:
  port: 8080
  servlet:
    context-path: /gwas/rest/api
  tomcat:
    accesslog:
      enabled: true
      directory: /var/log/gwas/restapi-access
      pattern: combined
      rotate: true
      condition-unless: skipLogging


spring:
  datasource:
    url: jdbc:oracle:thin:@(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=ora-spot-pub-hl.ebi.ac.uk)(PORT=1521))(CONNECT_DATA=(SERVER=DEDICATED)(SERVICE_NAME=SPOTPUB)))
    username:
    password:
#  jpa:
#    show-sql: true
#    properties:
#      hibernate.hibernate.format_sql : true

gwas-ui:
  url: https://www.ebi.ac.uk/gwas


