server:
  name: gwas-rest-api
  port: 80

logging:
  level:
    org:
      springframework: ERROR



spring:
  profiles:
    active: local
  datasource:
    url:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    username:
    password:

ensembl:
  server:
    url: https://rest.ensembl.org/variation/human
  mapping:
    version: 114

springdoc:
  swagger-ui:
    url: /rest-api-doc.yaml
    layout: BaseLayout
    #disable-swagger-default-url: true
    path: /v2/reference
  api-docs:
    enabled: true
    #path: /rest-api-doc


sumstats:
  link: http://ftp.ebi.ac.uk/pub/databases/gwas/summary_statistics/


terms-of-use:
  link: https://www.ebi.ac.uk/about/terms-of-use/

gwas-ui:
  url: https://www.ebi.ac.uk/gwas


cco:
  link: https://creativecommons.org/publicdomain/zero/1.0/
  exception:
    pmids: 30510241,36539618,37770635
    readme-text: Please Refer to ReadMe File

stats:
  url: "https://www.ebi.ac.uk/gwas/api/search/stats"

api:
  metadata:
    title: "GWAS Catalog Rest API 2.0"
    version: "2.0"
    apiReleaseDate: "2025-08-01"
    efoVersion: ""
    ensemblVersion: ""
    termsOfService: "https://www.ebi.ac.uk/about/terms-of-use/"
    commitHash: ${git.commit.id:UNKNOWN}
    license:
      name: "Apache License 2.0"
      url: "https://github.com/EBISPOT/gwas-rest-api/blob/master/LICENSE"
    contact:
      name: "GWAS Helpdesk"
      email: "gwas-info@ebi.ac.uk"
      url: "mailto:gwas-info@ebi.ac.uk"
    apiReference: "https://www.ebi.ac.uk/gwas/rest/api/v2/reference"
    apiDocumentation: "https://www.ebi.ac.uk/gwas/rest/api/v2/docs"


management:
  endpoints:
    web:
      exposure:
        include: info
