server:
  name: gwas-rest-api
  port: 80

logging:
  level:
    org:
      springframework: ERROR



spring:
  datasource:
    url:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    username:
    password:

ensembl:
  server:
    url: https://rest.ensembl.org/variation/human
  mapping:
    version: 113

springdoc:
  swagger-ui:
    url: /curation-doc.yaml
    layout: BaseLayout
    disable-swagger-default-url: true
    path: /documentation
  api-docs:
    path: /curation-doc


sumstats:
  link: http://ftp.ebi.ac.uk/pub/databases/gwas/summary_statistics/


terms-of-use:
  link: https://www.ebi.ac.uk/about/terms-of-use/

gwas-ui:
  url: https://www.ebi.ac.uk/gwas


cco:
  link: https://creativecommons.org/publicdomain/zero/1.0/
  exception:
    pmids: 30510241,36539618,37770635
    readme-text: Please Refer to ReadMe File

