server:
  name: gwas-rest-api
  port: 80

logging:
  level:
    org:
      springframework: ERROR



spring:
  datasource:
    url:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    username:
    password:

springdoc:
  swagger-ui:
    url: /curation-doc.yaml
    layout: BaseLayout
    disable-swagger-default-url: true
    path: /documentation
  api-docs:
    path: /curation-doc