server:
  port: 8087
  servlet:
    context-path: /gwas/rest/api



spring:
  datasource:
    url: jdbc:oracle:thin:@(DESCRIPTION=(ADDRESS=(PROTOCOL=TCP)(HOST=ora-spot-dev2-hl.ebi.ac.uk)(PORT=1521))(CONNECT_DATA=(SERVER=DEDICATED)(SERVICE_NAME=SPOTDV2)))
    #url: jdbc:oracle:thin:@ora-spot-pro-hl.ebi.ac.uk:1531/SPOTPRO
    username:
    password:
  jpa:
#    show-sql: true
#    properties:
#      hibernate.hibernate.format_sql : true


