server:
  name: gwas-rest-api
  port: 80

logging:
  level:
    org:
      springframework: ERROR



spring:
  datasource:
    url:
    driver-class-name: oracle.jdbc.driver.OracleDriver
    username:
    password:

ensembl:
  server:
    url: https://rest.ensembl.org/variation/human


springdoc:
  swagger-ui:
    url: /curation-doc.yaml
    layout: BaseLayout
    disable-swagger-default-url: true
    path: /documentation
  api-docs:
    path: /curation-doc


sumstats:
  link: http://ftp.ebi.ac.uk/pub/databases/gwas/summary_statistics/


terms-of-use:
  link: https://www.ebi.ac.uk/about/terms-of-use/